### PR TITLE
Setup travis

### PR DESCRIPTION
**Pull request by MOJOliciousFTW**

### CODE REVIEW

**Review by haggbart — APPROVED** [review]
Travis seems like a sensible addition to the project which can help increase the workflow since you don't have to test PRs locally as often, assuming the tests are good. :muscle:
all tests passed

**Comment by MOJOliciousFTW** [comment]
Travis is kinda neat. The .travis.yml file desribes the setup for the virtual machine to run the tests: ubuntu xenial, python 3.7, basically. I did set up some other stuff at travis-ci.org and coveralls.io to actually run the tests and to check how much of the code is tested (and get those neat badges that will appear).

**Comment by haggbart** [comment]
Being able to effortlessly test your code across a wide variety of systems is most definitely reassuring. If I'm not mistaken, it's possible to assign multiple distros and python versions at the same time?

Edit: Here, testing on multiple OS's and ignore failures on ones specified.
https://docs.travis-ci.com/user/multi-os/

**Comment by MOJOliciousFTW** [comment]
I haven`t done that before, only used the setup I intend to deploy on. I really like the idea of adding distros, makes a lot of sense, new distros are a potential issue with ROS for example. Maybe add bioinic and eoan? http://no.releases.ubuntu.com

**Comment by MOJOliciousFTW** [comment]
travis didn`t trigger on my build changes. reverted. probably better to set up travis locally to test this first.

**Comment by haggbart** [comment]
Looking forward to try this out :+1:

**Pull request merged**
