### PR TITLE
json getters

### PR DESCRIPTION
**Pull request by haggbart**

### CODE REVIEW

**Comment by MOJOliciousFTW** [comment]
I prefer pandas for data, can you change? something like this
import pandas as pd
df = pd.DataFrame(self._result, columns=['S', 'I', 'R'])
df['t'] = self._t
df.set_index('t', inplace=True)
print(df)
print(df.to_json(orient="index"))
print(df.to_json())

**Comment by haggbart** [comment]
I'll have a look

**Comment by MOJOliciousFTW** [comment]
Note: I had 2 seconds to write the comment above and a child on my keyboard 😅 without pandas is ofc perfectly fine, I just really like dataframes :)

**Comment by haggbart** [comment]
Starting to like it too! 👍

**Comment by haggbart** [comment]
Pandas is one of those packages that makes you realise how powerful dynamic typed languages like python can be, especially as a science tool. You can do so much with very little effort while enjoying benefits like GPU acceleration for fast data processing.

**Review by MOJOliciousFTW — APPROVED** [review]

**Pull request merged**
